<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\compatibility-policy.json" Link="compatibility-policy.json" />
    <EmbeddedResource Include="..\..\release-manifest-signing-public-key.pem" Link="release-manifest-signing-public-key.pem" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElectronicLogbook.Portable\ElectronicLogbook.Portable.csproj" />
  </ItemGroup>

</Project>
