namespace ElectronicLogbook.Portable;

public sealed record PortableLogbookEntry(
    DateOnly? Date,
    string? AircraftType,
    string? Registration,
    string? FlightNumber,
    string? From,
    string? To,
    string? Route,
    string? Details,
    decimal? MultiPilot,
    decimal? PilotInCommand,
    decimal? CoPilot,
    decimal? Dual,
    decimal? Instructor,
    decimal? Day,
    decimal? Night,
    decimal? InstrumentActual,
    decimal? InstrumentSimulated,
    int? TakeoffsDay,
    int? TakeoffsNight,
    int? LandingsDay,
    int? LandingsNight,
    int? IfrApproaches,
    int? Holding,
    int? Rnav,
    int? Circling,
    IReadOnlyDictionary<CustomFieldId, string?> CustomFields)
{
    public static PortableLogbookEntry Empty { get; } = new(
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        new Dictionary<CustomFieldId, string?>());
}

public sealed record CustomFieldDefinition(
    CustomFieldId Id,
    string Label,
    int Order,
    string? Description = null);
