namespace ElectronicLogbook.Portable;

public sealed record PortableLogbookWorkbookEntry(
    int? Year,
    int? Month,
    int? Day,
    string? Type,
    string? Reg,
    string? FlightId,
    string? Pic,
    string? OtherPilotOrCrew,
    string? From,
    string? To,
    string? Via,
    string? Remarks,
    bool? FlightReview,
    bool? InstrumentProficiencyCheck,
    bool? OperatorProficiencyCheck,
    IReadOnlyDictionary<CustomFieldId, string?> CustomFields,
    decimal? SeIcusDay,
    decimal? SeIcusNight,
    decimal? SeDualDay,
    decimal? SeDualNight,
    decimal? SeCommandDay,
    decimal? SeCommandNight,
    decimal? MeIcusDay,
    decimal? MeIcusNight,
    decimal? MeDualDay,
    decimal? MeDualNight,
    decimal? MeCommandDay,
    decimal? MeCommandNight,
    decimal? CopilotDay,
    decimal? CopilotNight,
    decimal? IfrIf,
    decimal? IfrSim,
    int? LandingsDay,
    int? LandingsNight,
    int? Ils,
    int? Vor,
    int? Rnp,
    int? Ndb,
    int? DgaCdi,
    int? DgaAzi,
    int? Circling)
{
    public static PortableLogbookWorkbookEntry Empty { get; } = new(
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        new Dictionary<CustomFieldId, string?>(),
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);

    public DateOnly? Date =>
        Year is { } year &&
        Month is { } month &&
        Day is { } day &&
        DateOnly.TryParse($"{year:D4}-{month:D2}-{day:D2}", out var date)
            ? date
            : null;
}
